# 1.1 파이썬이란
 - 데이터 과학 분야에서 파이썬 언어가 유용함을 설명함

# 1.2 파이썬 설치하기
- 파이썬 3와 넘파이, matplotlib을 본 책에서는 사용한다고 안내함
- 아나콘다도 설치할 것을 권장함

# 1.3 파이썬 인터프리터
- 인터프리터 모드(쉘 모드)로 기본 문법 안내
- 산술연산, 자료형, 변수, 리스트, 딕셔너리, bool, if, for, 함수에 대한 기본 문법 안내

# 1.4 파이썬 스크립트 파일
- 파이썬 스크립트 파일을 저장하고 실행함
- 클래스를 정의하고 인스턴스를 생성함

# 1.5 넘파이
- 넘파이의 ndarray에 대한 기본적인 기능들에 대해서 설명

## 1.5.1 넘파이 가져오기

In [1]:
import numpy as np

## 1.5.2 넘파이 배열 생성하기

In [2]:
x = np.array([1.0, 2.0, 3.0])
print("ndarray 'x' : ", x)
print("type of variable 'x' : ", type(x))
print("shape of ndarray 'x' : ", x.shape)

ndarray 'x' :  [1. 2. 3.]
type of variable 'x' :  <class 'numpy.ndarray'>
shape of ndarray 'x' :  (3,)


# 1.5.3 넘파이의 산술 연산
- 아래 코드에서 원소별, 즉 각 array의 같은 위치에 있는 원소끼리의 계산을 **'element-wise'**라고 한다.
    - 예를 들어 '원소별 곱셈'은 **'element-wise product'**라고 한다.

In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print("x + y : ",x+y) # 원소별 덧셈
print("x - y : ",x-y) # 원소별 뺄셈
print("x * y : ",x*y) # 원소별 곱셈
print("x / y : ",x/y) # 원소별 나눗셈

x + y :  [3. 6. 9.]
x - y :  [-1. -2. -3.]
x * y :  [ 2.  8. 18.]
x / y :  [0.5 0.5 0.5]


In [4]:
# broadcast 맛보기
x = np.array([1.0, 2.0, 3.0])
x/2.0

array([0.5, 1. , 1.5])

## 1.5.4 넘파이의 N차원 배열

In [5]:
A = np.array([[1, 2], [3, 4]])
print("A : \n", A)
print("shape of A : ", A.shape)
print("dtype of A : ", A.dtype)

A : 
 [[1 2]
 [3 4]]
shape of A :  (2, 2)
dtype of A :  int32


In [6]:
# 형상이 같은 배열일 경우 element-wise operation이 가능
B = np.array([[3,0],[0,6]])
print("A+B : \n", A+B)
print("A*B : \n", A*B)

A+B : 
 [[ 4  2]
 [ 3 10]]
A*B : 
 [[ 3  0]
 [ 0 24]]


In [7]:
# N차원 배열의 브로드캐스트
print("A : \n", A)
print("A*10 : \n", A*10)

A : 
 [[1 2]
 [3 4]]
A*10 : 
 [[10 20]
 [30 40]]


# 1.5.5 브로드캐스트

In [8]:
A = np.array([[1,2],[3,4]])
B = np.array([10,20])
print("A*B : \n",A*B) # B의 열 순서대로 A 행렬의 각 행에 곱해진다.

A*B : 
 [[10 40]
 [30 80]]


## 1.5.6 원소 접근

In [9]:
X = np.array([[51,55],[14,19],[0,4]])
print("X : \n",X)
print("X[0] : ",X[0]) # 0번째 행
print("X[0][1] : ",X[0][1]) # 0번째 행의 1번째 열

X : 
 [[51 55]
 [14 19]
 [ 0  4]]
X[0] :  [51 55]
X[0][1] :  55


In [ ]:
for i,row in enumerate(X): # 기존 책 내용에서 enumerate 추가, enumerate 함수가 궁금하다면 -> https://www.daleseo.com/python-enumerate/ 참고
    print("%d번째 행 : " %i,row)

### tip : 인덱스를 배열로 지정해 한 번에 여러 원소에 접근하는 법

In [ ]:
X = X.flatten() # x를 1차원 배열로 변환(평탄화)
print(X)
X[np.array([0,2,4])] # 인덱스가 0,2,4인 원소 얻기

In [ ]:
# 특정 조건을 만족하는 원소 얻기
print(X>15) # boolean array
print(X[X>15]) # True인 원소만 X 배열에서 출력

# 1.6 matplotlib

## 1.6.1 단순한 그래프 그리기
- **matplotlib 라이브러리의 pyplot 모듈**을 활용해서 그래프를 그릴 수 있음

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# 데이터 준비
x = np.arange(0, 6, 0.1) # 0에서 6까지 0.1 간격으로 생성
y = np.sin(x)

# 그래프 그리기
plt.plot(x, y)
plt.show()

## 1.6.2 pyplot의 기능
- 그래프 2개를 중첩해서 표현 가능
- 제목, 각 축의 이름 표시, 제목, linestyle, legend 기능

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# 데이터 준비
x = np.arange(0, 6, 0.1) # 0에서 6까지 0.1 간격으로 생성
y1 = np.sin(x)
y2 = np.cos(x)

# 그래프 그리기
plt.plot(x, y1, label="sin")
plt.plot(x, y2, linestyle="--", label="cos") # cos 함수는 점선으로 그리기
plt.xlabel("x") # x축 이름
plt.ylabel("y") # y축 이름
plt.title("sin & cos") # 제목
plt.legend()
plt.show()

## 1.6.3 이미지 표시하기
- pyplot 모듈에는 이미지를 표시해주는 메서드인 imshow()가 있음
- 이미지를 읽어서 메모리에 할당하는 모듈은 **matplotlib의 image 모듈이고 imread 메서드로 이미지를 읽는다.**

In [1]:
import matplotlib.pyplot as plt
import matplotlib.image as imread

img = imread('./images/fig 1-5.png')
plt.imshow(img)
plt.show

ModuleNotFoundError: No module named 'matplotlib'

In [2]:
!conda install matplotlib

^C
